# Generated by Django 6.0.3 on 2026-03-11 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100, unique=True)),
                ('content_type', models.CharField(choices=[('message', 'Message'), ('post', 'Post'), ('comment', 'Comment')], default='message', max_length=30)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('actioned', 'Actioned')], default='active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_id', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('harassment', 'Harassment or Abuse'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('spam_scam', 'Spam or Scam'), ('sexual_content', 'Non-consensual or Sexual Content'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.contentitem')),
            ],
        ),
        migrations.AddField(
            model_name='contentitem',
            name='reported_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='reports.reportedaccount'),
        ),
    ]
