# Generated by Django 6.0.3 on 2026-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_reporter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('harassment_or_bullying', 'Harassment or Bullying'), ('hate_or_discrimination', 'Hate or Discrimination'), ('threats_or_intimidation', 'Threats or Intimidation'), ('misinformation', 'False or misleading information'), ('scams_or_impersonation', 'Scams or impersonation'), ('sexual_content', 'Non-consensual or Sexual Content'), ('something_else', 'Other')], max_length=50),
        ),
    ]
