# Generated by Django 6.0.3 on 2026-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('harassment_or_bullying', 'Harassment or Bullying'), ('hate_or_discrimination', 'Hate or Discrimination'), ('threats_or_intimidation', 'Threats or Intimidation'), ('misinformation', 'False or Misleading Information'), ('scams_or_impersonation', 'Scams or Impersonation'), ('sexual_content', 'Sexual Abuse or Exploitation'), ('soft_report', 'Flagged for Review'), ('something_else', 'Other')], max_length=50),
        ),
    ]
